// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using magero_store.Data;

#nullable disable

namespace magero_store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250613172346_AddCategoryFeature")]
    partial class AddCategoryFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("magero_store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Computers and related accessories",
                            Name = "Computing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gaming equipment and accessories",
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("magero_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "High-performance gaming laptop with RTX 3080",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
                            Name = "Gaming Laptop",
                            Price = 1999.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Premium wireless earbuds with noise cancellation",
                            ImageUrl = "https://images.unsplash.com/photo-1590658087412-d1d9f559ef20",
                            Name = "Wireless Earbuds",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "32-inch 4K HDR Professional Monitor",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
                            Name = "4K Monitor",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "RGB Mechanical Gaming Keyboard",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212",
                            Name = "Mechanical Keyboard",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Wireless Gaming Mouse with 25K DPI",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46",
                            Name = "Gaming Mouse",
                            Price = 129.99m
                        });
                });

            modelBuilder.Entity("magero_store.Models.Product", b =>
                {
                    b.HasOne("magero_store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("magero_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
